- name: ec2 Create
  hosts: localhost
  connection: local
  vars_files:
    - aws_keys.yml
  tasks:
   - name: Creating EC2
     ec2:
       instance_type: t2.micro
       key_name: alina
       image: ami-030dbca661d402413
       region: eu-west-1
       group: default
       count: 1
       vpc_subnet_id: subnet-0f189f28f011b3d33
       wait: true
       assign_public_ip: yes
       state: 'present'
       instance_tags: '{"Name":"webserver","Type":"webserver"}'
     register: ec2
     tags: create

   - name: Add the newly created host so that we can further contact it
     add_host:
       name: "{{ item.public_ip }}"
       groups: webservers
     with_items: "{{ec2.instances}}"
     tags: create

   - name: Wait for the instances to boot by checking the ssh port
     wait_for: host="{{ item.public_ip }}" port=22 delay=60 timeout=300 state=started
     with_items: "{{ec2.instances}}"
     tags: create

   - name: Terminate instances that were previously launched
     ec2:
       region: eu-west-1
       state: 'absent'
       instance_ids: "{{ item.id }}"
     with_items: "{{ec2.instances}}"
     tags: terminate
