- name: ec2 Create
  hosts: localhost
  connection: local
  vars:
    region: eu-west-1
  vars_files:
    - aws_keys.yml
  tasks:
   - name: Creating EC2
     ec2:
       instance_type: t2.micro
       key_name: alina
       image: ami-030dbca661d402413
       region: "{{ region }}"
       group: default
       count: 1
       vpc_subnet_id: subnet-0f189f28f011b3d33
       wait: true
       assign_public_ip: yes
       state: 'present'
       instance_tags: '{"Name":"webserver","Type":"webserver"}'
     register: ec2
     tags: create

   - name: Gather EC2 facts
     ec2_instance_facts:
       region: "{{ region }}"
       filters:
         "tag:Type": "webserver"
     register: ec2
     tags: configure, terminate
   - debug: var=ec2
     tags: configure, terminate

   - name: Add the newly created host so that we can further contact it
     add_host:
       name: "{{ item.public_ip_address }}"
       groups: webservers
     with_items: "{{ec2.instances}}"
     tags: configure

   - name: Wait for the instances to boot by checking the ssh port
     wait_for: host="{{ item.public_ip }}" port=22 delay=60 timeout=300 state=started
     with_items: "{{ec2.instances}}"
     tags: create

   - name: Terminate EC2 Instance(s)
     ec2:
       instance_ids: '{{ item.instance_id }}'
       state: absent
       region: "{{ region }}"
     with_items: "{{ ec2.instances }}"
     tags: terminate

- hosts: webservers
  remote_user: ec2-user
  become: yes
  gather_facts: no
  tasks:
   - name: remove the apache package
     package:
       name: httpd
       state: present
   - service:
       name: httpd
       state: started
       enabled: yes
  tags: configure
