- name: ec2 Create
  hosts: localhost
  connection: local
  vars_files:
    - aws_keys.yml
  tasks:
   - name: Creating EC2
     ec2:
       instance_type: t2.micro
       key_name: webserver
       image: ami-0c6b1d09930fac512
       region: us-east-1
       group: default
       count: 1
       vpc_subnet_id: subnet-e453f3ca
       wait: yes
       assign_public_ip: yes
       instance_tags: '{"Name":"webserver"}'
     register: ec2_1

   - name: Add the newly created host so that we can further contact it
     add_host:
       name: "{{ item.public_ip }}"
       groups: webservers
     with_items: "{{ ec2_1.instances }}"
